abstract: Mirror remote repositories to local subversion repository
author: Chia-liang Kao <clkao@clkao.org>
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
name: SVN-Mirror
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0
  Date::Format: 0
  File::chdir: 0
  SVN::Core: 1.0.7
  SVN::Simple::Edit: 0
  Term::ReadKey: 0
  URI::Escape: 0
version: 0.71
